# ruff: noqa: E501

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class TableContract:
    name: str
    object_type: str
    grain: str
    unique_key: tuple[str, ...]
    required_columns: tuple[str, ...]
    rerun_rule: str
    lineage_columns: tuple[str, ...]
    freshness_column: str | None = None
    artifact_columns: tuple[str, ...] = ()
    notes: str = ""
    ticket_ids: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class ChecklistItem:
    ticket_id: str
    title: str
    required_objects: tuple[str, ...]
    required_files: tuple[str, ...]
    optional_objects: tuple[str, ...] = ()
    optional_files: tuple[str, ...] = ()
    notes: str = ""


def _contract(
    name: str,
    *,
    grain: str,
    unique_key: tuple[str, ...],
    required_columns: tuple[str, ...],
    rerun_rule: str,
    lineage_columns: tuple[str, ...],
    freshness_column: str | None = None,
    artifact_columns: tuple[str, ...] = (),
    notes: str = "",
    ticket_ids: tuple[str, ...],
    object_type: str = "table",
) -> TableContract:
    return TableContract(
        name=name,
        object_type=object_type,
        grain=grain,
        unique_key=unique_key,
        required_columns=required_columns,
        rerun_rule=rerun_rule,
        lineage_columns=lineage_columns,
        freshness_column=freshness_column,
        artifact_columns=artifact_columns,
        notes=notes,
        ticket_ids=ticket_ids,
    )


CONTRACTS: tuple[TableContract, ...] = (
    _contract(
        "dim_symbol",
        grain="1 row per symbol",
        unique_key=("symbol",),
        required_columns=("symbol", "company_name", "market", "is_common_stock", "updated_at"),
        rerun_rule="UPSERT by symbol.",
        lineage_columns=("source", "as_of_date", "updated_at"),
        freshness_column="updated_at",
        ticket_ids=("T000", "T001"),
    ),
    _contract(
        "dim_trading_calendar",
        grain="1 row per trading_date",
        unique_key=("trading_date",),
        required_columns=(
            "trading_date",
            "is_trading_day",
            "prev_trading_date",
            "next_trading_date",
        ),
        rerun_rule="UPSERT by trading_date.",
        lineage_columns=("source", "source_confidence", "is_override", "updated_at"),
        freshness_column="updated_at",
        ticket_ids=("T000", "T001"),
    ),
    _contract(
        "fact_daily_ohlcv",
        grain="1 row per trading_date x symbol",
        unique_key=("trading_date", "symbol"),
        required_columns=(
            "trading_date",
            "symbol",
            "open",
            "high",
            "low",
            "close",
            "volume",
            "ingested_at",
        ),
        rerun_rule="Idempotent INSERT/REPLACE on primary key.",
        lineage_columns=("source", "source_notes_json", "ingested_at"),
        freshness_column="trading_date",
        ticket_ids=("T002",),
    ),
    _contract(
        "fact_fundamentals_snapshot",
        grain="1 row per as_of_date x symbol",
        unique_key=("as_of_date", "symbol"),
        required_columns=(
            "as_of_date",
            "symbol",
            "fiscal_year",
            "report_code",
            "source_doc_id",
            "ingested_at",
        ),
        rerun_rule="Idempotent UPSERT on as_of_date x symbol.",
        lineage_columns=("source", "disclosed_at", "source_doc_id", "ingested_at"),
        freshness_column="as_of_date",
        ticket_ids=("T002",),
    ),
    _contract(
        "fact_news_item",
        grain="1 row per canonical news_id",
        unique_key=("news_id",),
        required_columns=(
            "news_id",
            "signal_date",
            "published_at",
            "title",
            "link",
            "canonical_link",
            "ingested_at",
        ),
        rerun_rule="Deduplicate by news_id / canonical_link.",
        lineage_columns=(
            "source",
            "query_keyword",
            "query_bucket",
            "match_method_json",
            "ingested_at",
        ),
        freshness_column="published_at",
        ticket_ids=("T002",),
    ),
    _contract(
        "fact_feature_snapshot",
        grain="1 row per as_of_date x symbol x feature_name",
        unique_key=("as_of_date", "symbol", "feature_name"),
        required_columns=(
            "run_id",
            "as_of_date",
            "symbol",
            "feature_name",
            "feature_value",
            "created_at",
        ),
        rerun_rule="Delete+rebuild or INSERT/REPLACE by primary key.",
        lineage_columns=("run_id", "feature_group", "source_version", "created_at"),
        freshness_column="as_of_date",
        ticket_ids=("T003",),
    ),
    _contract(
        "fact_forward_return_label",
        grain="1 row per as_of_date x symbol x horizon",
        unique_key=("as_of_date", "symbol", "horizon"),
        required_columns=(
            "run_id",
            "as_of_date",
            "symbol",
            "horizon",
            "entry_date",
            "exit_date",
            "label_available_flag",
            "created_at",
        ),
        rerun_rule="Idempotent label build by primary key and horizon.",
        lineage_columns=("run_id", "baseline_type", "notes_json", "created_at"),
        freshness_column="as_of_date",
        ticket_ids=("T003",),
    ),
    _contract(
        "fact_market_regime_snapshot",
        grain="1 row per as_of_date x market_scope",
        unique_key=("as_of_date", "market_scope"),
        required_columns=(
            "run_id",
            "as_of_date",
            "market_scope",
            "regime_state",
            "regime_score",
            "created_at",
        ),
        rerun_rule="INSERT/REPLACE by as_of_date x market_scope.",
        lineage_columns=("run_id", "notes_json", "created_at"),
        freshness_column="as_of_date",
        ticket_ids=("T003",),
    ),
    _contract(
        "fact_investor_flow",
        grain="1 row per trading_date x symbol",
        unique_key=("trading_date", "symbol"),
        required_columns=(
            "run_id",
            "trading_date",
            "symbol",
            "foreign_net_value",
            "institution_net_value",
            "created_at",
        ),
        rerun_rule="Idempotent INSERT/REPLACE by trading_date x symbol.",
        lineage_columns=("run_id", "source", "source_notes_json", "created_at"),
        freshness_column="trading_date",
        ticket_ids=("T004",),
    ),
    _contract(
        "fact_prediction",
        grain="1 row per as_of_date x symbol x horizon x prediction_version",
        unique_key=("as_of_date", "symbol", "horizon", "prediction_version"),
        required_columns=(
            "run_id",
            "as_of_date",
            "symbol",
            "horizon",
            "prediction_version",
            "ranking_version",
            "created_at",
        ),
        rerun_rule="Prediction snapshot is append-only across versions, idempotent within primary key.",
        lineage_columns=(
            "run_id",
            "model_version",
            "training_run_id",
            "model_spec_id",
            "active_alpha_model_id",
            "source_notes_json",
            "fallback_reason",
            "created_at",
        ),
        freshness_column="as_of_date",
        ticket_ids=("T004", "T006"),
    ),
    _contract(
        "fact_ranking",
        grain="1 row per as_of_date x symbol x horizon x ranking_version",
        unique_key=("as_of_date", "symbol", "horizon", "ranking_version"),
        required_columns=(
            "run_id",
            "as_of_date",
            "symbol",
            "horizon",
            "ranking_version",
            "final_selection_value",
            "created_at",
        ),
        rerun_rule="Append by ranking_version, idempotent within primary key.",
        lineage_columns=(
            "run_id",
            "top_reason_tags_json",
            "risk_flags_json",
            "eligibility_notes_json",
            "created_at",
        ),
        freshness_column="as_of_date",
        ticket_ids=("T003", "T004", "T006"),
    ),
    _contract(
        "fact_selection_outcome",
        grain="1 row per selection_date x symbol x horizon x ranking_version",
        unique_key=("selection_date", "symbol", "horizon", "ranking_version"),
        required_columns=(
            "selection_date",
            "symbol",
            "horizon",
            "ranking_version",
            "evaluation_run_id",
            "outcome_status",
            "updated_at",
        ),
        rerun_rule="Outcome rows are updated in place by same selection snapshot key.",
        lineage_columns=(
            "evaluation_run_id",
            "prediction_version_at_selection",
            "training_run_id_at_selection",
            "model_spec_id_at_selection",
            "active_alpha_model_id_at_selection",
            "source_label_version",
            "updated_at",
        ),
        freshness_column="selection_date",
        ticket_ids=("T005",),
    ),
    _contract(
        "fact_evaluation_summary",
        grain="1 row per summary_date x window_type x horizon x ranking_version x segment_type x segment_value",
        unique_key=(
            "summary_date",
            "window_type",
            "horizon",
            "ranking_version",
            "segment_type",
            "segment_value",
        ),
        required_columns=(
            "summary_date",
            "window_type",
            "horizon",
            "ranking_version",
            "segment_type",
            "segment_value",
            "evaluation_run_id",
            "created_at",
        ),
        rerun_rule="Append or replace within summary grain.",
        lineage_columns=("evaluation_run_id", "created_at"),
        freshness_column="summary_date",
        ticket_ids=("T005",),
    ),
    _contract(
        "fact_calibration_diagnostic",
        grain="1 row per diagnostic_date x horizon x ranking_version x bin_type x bin_value",
        unique_key=("diagnostic_date", "horizon", "ranking_version", "bin_type", "bin_value"),
        required_columns=(
            "diagnostic_date",
            "horizon",
            "ranking_version",
            "bin_type",
            "bin_value",
            "evaluation_run_id",
            "created_at",
        ),
        rerun_rule="Replace per diagnostic window and bin.",
        lineage_columns=("evaluation_run_id", "created_at"),
        freshness_column="diagnostic_date",
        ticket_ids=("T005",),
    ),
    _contract(
        "fact_model_training_run",
        grain="1 row per training_run_id",
        unique_key=("training_run_id",),
        required_columns=(
            "training_run_id",
            "run_id",
            "model_domain",
            "model_version",
            "horizon",
            "train_end_date",
            "status",
            "created_at",
        ),
        rerun_rule="Append-only registry; new run gets new training_run_id.",
        lineage_columns=(
            "run_id",
            "artifact_uri",
            "diagnostic_artifact_uri",
            "metadata_json",
            "created_at",
        ),
        freshness_column="train_end_date",
        artifact_columns=("artifact_uri", "diagnostic_artifact_uri"),
        ticket_ids=("T006", "T010"),
    ),
    _contract(
        "fact_alpha_active_model",
        grain="1 row per active_alpha_model_id",
        unique_key=("active_alpha_model_id",),
        required_columns=(
            "active_alpha_model_id",
            "horizon",
            "model_spec_id",
            "training_run_id",
            "effective_from_date",
            "active_flag",
            "updated_at",
        ),
        rerun_rule="Append-only active alpha registry; freeze/rollback creates new rows.",
        lineage_columns=(
            "training_run_id",
            "model_spec_id",
            "promotion_type",
            "source_type",
            "updated_at",
        ),
        freshness_column="effective_from_date",
        ticket_ids=("T006",),
    ),
    _contract(
        "fact_alpha_shadow_prediction",
        grain="1 row per selection_date x symbol x horizon x model_spec_id",
        unique_key=("selection_date", "symbol", "horizon", "model_spec_id"),
        required_columns=(
            "run_id",
            "selection_date",
            "symbol",
            "horizon",
            "model_spec_id",
            "training_run_id",
            "created_at",
        ),
        rerun_rule="Replace per selection_date x symbol x horizon x model_spec_id.",
        lineage_columns=("run_id", "training_run_id", "model_spec_id", "created_at"),
        freshness_column="selection_date",
        ticket_ids=("T006",),
    ),
    _contract(
        "fact_alpha_shadow_ranking",
        grain="1 row per selection_date x symbol x horizon x model_spec_id",
        unique_key=("selection_date", "symbol", "horizon", "model_spec_id"),
        required_columns=(
            "run_id",
            "selection_date",
            "symbol",
            "horizon",
            "model_spec_id",
            "training_run_id",
            "created_at",
        ),
        rerun_rule="Replace per selection_date x symbol x horizon x model_spec_id.",
        lineage_columns=("run_id", "training_run_id", "model_spec_id", "created_at"),
        freshness_column="selection_date",
        ticket_ids=("T006",),
    ),
    _contract(
        "fact_alpha_shadow_selection_outcome",
        grain="1 row per selection_date x symbol x horizon x model_spec_id",
        unique_key=("selection_date", "symbol", "horizon", "model_spec_id"),
        required_columns=(
            "selection_date",
            "symbol",
            "horizon",
            "model_spec_id",
            "evaluation_run_id",
            "outcome_status",
            "updated_at",
        ),
        rerun_rule="Replace per selection_date x symbol x horizon x model_spec_id.",
        lineage_columns=(
            "training_run_id",
            "model_spec_id",
            "source_label_version",
            "evaluation_run_id",
            "updated_at",
        ),
        freshness_column="selection_date",
        ticket_ids=("T006",),
    ),
    _contract(
        "fact_alpha_shadow_evaluation_summary",
        grain="1 row per summary_date x window_type x horizon x model_spec_id x segment_value",
        unique_key=("summary_date", "window_type", "horizon", "model_spec_id", "segment_value"),
        required_columns=(
            "summary_date",
            "window_type",
            "horizon",
            "model_spec_id",
            "segment_value",
            "evaluation_run_id",
            "created_at",
        ),
        rerun_rule="Replace within summary grain.",
        lineage_columns=("evaluation_run_id", "model_spec_id", "created_at"),
        freshness_column="summary_date",
        ticket_ids=("T006",),
    ),
    _contract(
        "fact_alpha_promotion_test",
        grain=(
            "1 row per promotion_date x horizon x incumbent_model_spec_id x "
            "challenger_model_spec_id x loss_name"
        ),
        unique_key=(
            "promotion_date",
            "horizon",
            "incumbent_model_spec_id",
            "challenger_model_spec_id",
            "loss_name",
        ),
        required_columns=(
            "promotion_date",
            "horizon",
            "incumbent_model_spec_id",
            "challenger_model_spec_id",
            "loss_name",
            "decision",
            "created_at",
        ),
        rerun_rule="Replace within promotion test grain.",
        lineage_columns=("detail_json", "decision", "created_at"),
        freshness_column="promotion_date",
        ticket_ids=("T006",),
    ),
    _contract(
        "fact_model_member_prediction",
        grain="1 row per training_run_id x as_of_date x symbol x horizon x prediction_role x member_name",
        unique_key=(
            "training_run_id",
            "as_of_date",
            "symbol",
            "horizon",
            "prediction_role",
            "member_name",
        ),
        required_columns=(
            "training_run_id",
            "as_of_date",
            "symbol",
            "horizon",
            "prediction_role",
            "member_name",
            "created_at",
        ),
        rerun_rule="Idempotent within training run/member grain.",
        lineage_columns=("training_run_id", "model_version", "fallback_reason", "created_at"),
        freshness_column="as_of_date",
        ticket_ids=("T006",),
    ),
    _contract(
        "fact_intraday_candidate_session",
        grain="1 row per session_date x symbol x horizon x ranking_version",
        unique_key=("session_date", "symbol", "horizon", "ranking_version"),
        required_columns=(
            "run_id",
            "selection_date",
            "session_date",
            "symbol",
            "horizon",
            "ranking_version",
            "created_at",
            "updated_at",
        ),
        rerun_rule="Refresh candidate session by session_date/horizon/ranking_version key.",
        lineage_columns=("run_id", "checkpoint_plan_json", "notes_json", "updated_at"),
        freshness_column="session_date",
        ticket_ids=("T007",),
    ),
    _contract(
        "fact_intraday_final_action",
        object_type="view",
        grain="1 row per session_date x symbol x horizon x checkpoint_time x ranking_version",
        unique_key=("session_date", "symbol", "horizon", "checkpoint_time", "ranking_version"),
        required_columns=(
            "run_id",
            "session_date",
            "symbol",
            "horizon",
            "checkpoint_time",
            "ranking_version",
            "final_action",
            "created_at",
        ),
        rerun_rule="Compatibility view over meta decision final action snapshot.",
        lineage_columns=(
            "active_policy_candidate_id",
            "active_meta_model_id",
            "active_meta_training_run_id",
            "created_at",
        ),
        freshness_column="session_date",
        notes="Compatibility layer for final intraday action contract.",
        ticket_ids=("T007", "T010"),
    ),
    _contract(
        "fact_intraday_meta_prediction",
        grain="1 row per session_date x symbol x horizon x checkpoint_time x ranking_version",
        unique_key=("session_date", "symbol", "horizon", "checkpoint_time", "ranking_version"),
        required_columns=(
            "run_id",
            "session_date",
            "symbol",
            "horizon",
            "checkpoint_time",
            "ranking_version",
            "predicted_class",
            "created_at",
        ),
        rerun_rule="Idempotent scoring snapshot for active meta model.",
        lineage_columns=(
            "active_meta_model_id",
            "training_run_id",
            "fallback_reason",
            "created_at",
        ),
        freshness_column="session_date",
        ticket_ids=("T010",),
    ),
    _contract(
        "fact_intraday_meta_decision",
        grain="1 row per session_date x symbol x horizon x checkpoint_time x ranking_version",
        unique_key=("session_date", "symbol", "horizon", "checkpoint_time", "ranking_version"),
        required_columns=(
            "run_id",
            "session_date",
            "symbol",
            "horizon",
            "checkpoint_time",
            "ranking_version",
            "adjusted_action",
            "final_action",
            "created_at",
        ),
        rerun_rule="Bounded overlay materialization replaces same primary key only.",
        lineage_columns=(
            "active_policy_candidate_id",
            "active_meta_model_id",
            "active_meta_training_run_id",
            "fallback_reason",
            "created_at",
        ),
        freshness_column="session_date",
        ticket_ids=("T010",),
    ),
    _contract(
        "fact_intraday_active_meta_model",
        grain="1 row per active_meta_model_id",
        unique_key=("active_meta_model_id",),
        required_columns=(
            "active_meta_model_id",
            "horizon",
            "panel_name",
            "training_run_id",
            "effective_from_date",
            "active_flag",
            "updated_at",
        ),
        rerun_rule="Append-only registry; freeze/rollback creates new rows.",
        lineage_columns=(
            "training_run_id",
            "threshold_payload_json",
            "calibration_summary_json",
            "rollback_of_active_meta_model_id",
            "updated_at",
        ),
        freshness_column="effective_from_date",
        ticket_ids=("T010",),
    ),
    _contract(
        "fact_portfolio_target_book",
        grain="1 row per as_of_date x execution_mode x symbol",
        unique_key=("as_of_date", "execution_mode", "symbol"),
        required_columns=(
            "run_id",
            "as_of_date",
            "execution_mode",
            "symbol",
            "target_weight",
            "target_notional",
            "target_shares",
            "created_at",
        ),
        rerun_rule="INSERT OR REPLACE by primary key.",
        lineage_columns=(
            "portfolio_policy_id",
            "portfolio_policy_version",
            "notes_json",
            "created_at",
        ),
        freshness_column="as_of_date",
        ticket_ids=("T011",),
    ),
    _contract(
        "fact_portfolio_rebalance_plan",
        grain="1 row per as_of_date x execution_mode x symbol",
        unique_key=("as_of_date", "execution_mode", "symbol"),
        required_columns=(
            "run_id",
            "as_of_date",
            "execution_mode",
            "symbol",
            "rebalance_action",
            "created_at",
        ),
        rerun_rule="INSERT OR REPLACE by primary key.",
        lineage_columns=(
            "portfolio_policy_id",
            "portfolio_policy_version",
            "gate_status",
            "notes_json",
            "created_at",
        ),
        freshness_column="as_of_date",
        ticket_ids=("T011",),
    ),
    _contract(
        "fact_portfolio_position_snapshot",
        grain="1 row per snapshot_date x execution_mode x symbol",
        unique_key=(
            "snapshot_date",
            "execution_mode",
            "portfolio_policy_id",
            "portfolio_policy_version",
            "symbol",
        ),
        required_columns=(
            "run_id",
            "snapshot_date",
            "execution_mode",
            "portfolio_policy_id",
            "portfolio_policy_version",
            "symbol",
            "shares",
            "market_value",
            "created_at",
        ),
        rerun_rule="Replace per snapshot_date x execution_mode x symbol.",
        lineage_columns=(
            "portfolio_policy_id",
            "portfolio_policy_version",
            "source_rebalance_run_id",
            "notes_json",
            "created_at",
        ),
        freshness_column="snapshot_date",
        ticket_ids=("T011",),
    ),
    _contract(
        "fact_portfolio_nav_snapshot",
        grain="1 row per snapshot_date x execution_mode x portfolio_policy_id x portfolio_policy_version",
        unique_key=(
            "snapshot_date",
            "execution_mode",
            "portfolio_policy_id",
            "portfolio_policy_version",
        ),
        required_columns=(
            "run_id",
            "snapshot_date",
            "execution_mode",
            "portfolio_policy_id",
            "portfolio_policy_version",
            "nav_value",
            "cash_weight",
            "created_at",
        ),
        rerun_rule="Append by policy/version/date snapshot.",
        lineage_columns=("run_id", "source_position_run_id", "notes_json", "created_at"),
        freshness_column="snapshot_date",
        ticket_ids=("T011",),
    ),
    _contract(
        "fact_job_run",
        grain="1 row per run_id",
        unique_key=("run_id",),
        required_columns=(
            "run_id",
            "job_name",
            "trigger_type",
            "status",
            "started_at",
            "root_run_id",
            "created_at",
        ),
        rerun_rule="Append-only run registry; recovery gets new run_id.",
        lineage_columns=(
            "root_run_id",
            "parent_run_id",
            "recovery_of_run_id",
            "policy_id",
            "policy_version",
            "created_at",
        ),
        freshness_column="started_at",
        ticket_ids=("T012",),
    ),
    _contract(
        "fact_job_step_run",
        grain="1 row per step_run_id",
        unique_key=("step_run_id",),
        required_columns=(
            "step_run_id",
            "job_run_id",
            "step_name",
            "step_order",
            "status",
            "started_at",
            "created_at",
        ),
        rerun_rule="Append-only per job run step.",
        lineage_columns=("job_run_id", "details_json", "created_at"),
        freshness_column="started_at",
        ticket_ids=("T012",),
    ),
    _contract(
        "fact_health_snapshot",
        grain="1 row per snapshot_at x health_scope x component_name x metric_name",
        unique_key=("snapshot_at", "health_scope", "component_name", "metric_name"),
        required_columns=(
            "snapshot_at",
            "health_scope",
            "component_name",
            "metric_name",
            "status",
            "created_at",
        ),
        rerun_rule="Append snapshot history; latest view resolves current truth.",
        lineage_columns=("job_run_id", "details_json", "created_at"),
        freshness_column="snapshot_at",
        ticket_ids=("T012",),
    ),
    _contract(
        "fact_latest_app_snapshot",
        grain="1 row per snapshot_id, canonical latest resolved by vw_latest_app_snapshot",
        unique_key=("snapshot_id",),
        required_columns=(
            "snapshot_id",
            "snapshot_ts",
            "as_of_date",
            "health_status",
            "latest_report_bundle_id",
            "created_at",
        ),
        rerun_rule="Append-only snapshots; latest view must be unique.",
        lineage_columns=(
            "latest_daily_bundle_run_id",
            "latest_evaluation_run_id",
            "latest_intraday_run_id",
            "latest_portfolio_run_id",
            "created_at",
        ),
        freshness_column="snapshot_ts",
        ticket_ids=("T013",),
    ),
    _contract(
        "fact_latest_report_index",
        grain="1 row per report_index_id, canonical latest resolved by report_type",
        unique_key=("report_index_id",),
        required_columns=(
            "report_index_id",
            "report_type",
            "report_key",
            "generated_ts",
            "status",
            "artifact_path",
            "created_at",
        ),
        rerun_rule="INSERT OR REPLACE by report artifact hash; latest view by report_type.",
        lineage_columns=("run_id", "summary_json", "created_at"),
        freshness_column="generated_ts",
        artifact_columns=("artifact_path",),
        ticket_ids=("T013",),
    ),
    _contract(
        "fact_release_candidate_check",
        grain="1 row per release_candidate_check_id, canonical latest resolved by check_name",
        unique_key=("release_candidate_check_id",),
        required_columns=(
            "release_candidate_check_id",
            "check_ts",
            "environment",
            "check_name",
            "status",
            "severity",
            "created_at",
        ),
        rerun_rule="Append-only checklist history; latest view by check_name.",
        lineage_columns=("detail_json", "recommended_action", "created_at"),
        freshness_column="check_ts",
        ticket_ids=("T013",),
    ),
    _contract(
        "fact_ui_data_freshness_snapshot",
        grain="1 row per snapshot_ts x page_name x dataset_name",
        unique_key=("freshness_snapshot_id",),
        required_columns=(
            "freshness_snapshot_id",
            "snapshot_ts",
            "page_name",
            "dataset_name",
            "warning_level",
            "stale_flag",
            "created_at",
        ),
        rerun_rule="Append snapshot history; latest view by page_name x dataset_name.",
        lineage_columns=("notes", "created_at"),
        freshness_column="snapshot_ts",
        ticket_ids=("T013",),
    ),
)


CONTRACTS_BY_NAME: dict[str, TableContract] = {contract.name: contract for contract in CONTRACTS}


TICKET_CHECKLIST: tuple[ChecklistItem, ...] = (
    ChecklistItem(
        ticket_id="T000",
        title="Foundation / bootstrap / bot-first skeleton",
        required_objects=("dim_symbol", "dim_trading_calendar"),
        required_files=(
            "README.md",
            "pyproject.toml",
            "app/settings.py",
            "scripts/bootstrap.py",
            "app/discord_bot/service.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T001",
        title="Universe / calendar / provider activation",
        required_objects=("dim_symbol", "dim_trading_calendar"),
        required_files=(
            "scripts/sync_universe.py",
            "scripts/sync_trading_calendar.py",
            "scripts/provider_smoke_check.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T002",
        title="Core research ingestion",
        required_objects=("fact_daily_ohlcv", "fact_fundamentals_snapshot", "fact_news_item"),
        required_files=(
            "scripts/sync_daily_ohlcv.py",
            "scripts/sync_fundamentals_snapshot.py",
            "scripts/sync_news_metadata.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T003",
        title="Feature store / labels / explanatory ranking",
        required_objects=(
            "fact_feature_snapshot",
            "fact_forward_return_label",
            "fact_market_regime_snapshot",
            "fact_ranking",
        ),
        required_files=(
            "scripts/build_feature_store.py",
            "scripts/build_forward_labels.py",
            "scripts/build_market_regime_snapshot.py",
            "scripts/materialize_explanatory_ranking.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T004",
        title="Flow / selection v1 / discord report",
        required_objects=("fact_investor_flow", "fact_prediction"),
        required_files=(
            "scripts/sync_investor_flow.py",
            "scripts/materialize_selection_engine_v1.py",
            "scripts/render_discord_eod_report.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T005",
        title="Postmortem evaluation / calibration",
        required_objects=(
            "fact_selection_outcome",
            "fact_evaluation_summary",
            "fact_calibration_diagnostic",
        ),
        required_files=(
            "scripts/materialize_selection_outcomes.py",
            "scripts/materialize_prediction_evaluation.py",
            "scripts/materialize_calibration_diagnostics.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T006",
        title="ML alpha v1 / selection v2",
        required_objects=(
            "fact_model_training_run",
            "fact_model_member_prediction",
            "fact_prediction",
            "fact_ranking",
        ),
        required_files=(
            "scripts/build_model_training_dataset.py",
            "scripts/train_alpha_model_v1.py",
            "scripts/materialize_alpha_predictions_v1.py",
            "scripts/materialize_selection_engine_v2.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T007",
        title="Intraday candidate assist",
        required_objects=("fact_intraday_candidate_session", "fact_intraday_final_action"),
        required_files=(
            "scripts/materialize_intraday_candidate_session.py",
            "scripts/materialize_intraday_signal_snapshots.py",
            "scripts/materialize_intraday_entry_decisions.py",
            "scripts/evaluate_intraday_timing_layer.py",
        ),
        optional_objects=("fact_intraday_timing_outcome",),
    ),
    ChecklistItem(
        ticket_id="T008",
        title="Regime-aware intraday comparison",
        required_objects=(
            "fact_intraday_market_context_snapshot",
            "fact_intraday_regime_adjustment",
            "fact_intraday_adjusted_entry_decision",
            "fact_intraday_strategy_comparison",
            "fact_intraday_timing_calibration",
        ),
        required_files=(
            "scripts/materialize_intraday_market_context_snapshots.py",
            "scripts/materialize_intraday_regime_adjustments.py",
            "scripts/evaluate_intraday_strategy_comparison.py",
            "scripts/materialize_intraday_timing_calibration.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T009",
        title="Intraday policy calibration framework",
        required_objects=(
            "fact_intraday_policy_experiment_run",
            "fact_intraday_policy_candidate",
            "fact_intraday_policy_evaluation",
            "fact_intraday_policy_ablation_result",
            "fact_intraday_policy_selection_recommendation",
            "fact_intraday_active_policy",
        ),
        required_files=(
            "scripts/materialize_intraday_policy_candidates.py",
            "scripts/run_intraday_policy_calibration.py",
            "scripts/materialize_intraday_policy_recommendations.py",
            "scripts/freeze_intraday_active_policy.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T010",
        title="Intraday meta-model overlay",
        required_objects=(
            "fact_intraday_meta_prediction",
            "fact_intraday_meta_decision",
            "fact_intraday_active_meta_model",
        ),
        required_files=(
            "scripts/build_intraday_meta_training_dataset.py",
            "scripts/train_intraday_meta_models.py",
            "scripts/materialize_intraday_meta_predictions.py",
            "scripts/materialize_intraday_final_actions.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T011",
        title="Integrated portfolio layer",
        required_objects=(
            "fact_portfolio_target_book",
            "fact_portfolio_rebalance_plan",
            "fact_portfolio_position_snapshot",
            "fact_portfolio_nav_snapshot",
        ),
        required_files=(
            "scripts/build_portfolio_candidate_book.py",
            "scripts/materialize_portfolio_target_book.py",
            "scripts/materialize_portfolio_rebalance_plan.py",
            "scripts/materialize_portfolio_nav.py",
        ),
    ),
    ChecklistItem(
        ticket_id="T012",
        title="Ops hardening / health dashboard",
        required_objects=(
            "fact_job_run",
            "fact_job_step_run",
            "fact_pipeline_dependency_state",
            "fact_health_snapshot",
            "fact_disk_watermark_event",
            "fact_retention_cleanup_run",
            "fact_alert_event",
            "fact_recovery_action",
            "fact_active_ops_policy",
        ),
        required_files=(
            "scripts/run_daily_research_pipeline.py",
            "scripts/materialize_health_snapshots.py",
            "scripts/render_ops_report.py",
            "scripts/validate_ops_framework.py",
            "config/ops/default_ops_policy.yaml",
        ),
    ),
    ChecklistItem(
        ticket_id="T013",
        title="Final workflow / Discord bot / release polish",
        required_objects=(
            "fact_latest_app_snapshot",
            "fact_latest_report_index",
            "fact_release_candidate_check",
            "fact_ui_data_freshness_snapshot",
        ),
        required_files=(
            "scripts/build_report_index.py",
            "scripts/materialize_discord_bot_read_store.py",
            "scripts/run_discord_bot.py",
            "scripts/validate_release_candidate.py",
            "docs/USER_GUIDE.md",
            "docs/WORKFLOW_DAILY.md",
            "docs/GLOSSARY.md",
            "docs/KNOWN_LIMITATIONS.md",
        ),
        optional_files=("docs/REPORTS_AND_PAGES.md",),
    ),
)


TICKET_CHECKLIST_BY_ID: dict[str, ChecklistItem] = {
    item.ticket_id: item for item in TICKET_CHECKLIST
}


def representative_contracts() -> tuple[TableContract, ...]:
    return CONTRACTS


def get_contract(name: str) -> TableContract:
    return CONTRACTS_BY_NAME[name]


def get_ticket_checklist() -> tuple[ChecklistItem, ...]:
    return TICKET_CHECKLIST


def resolve_repo_path(project_root: Path, relative_path: str) -> Path:
    return (project_root / relative_path).resolve()
