accounts:
  revenue:
    - 매출액
    - 수익(매출액)
    - 영업수익
    - 보험영업수익
    - 이자수익
  operating_income:
    - 영업이익
  net_income:
    - 당기순이익
    - 당기순이익(손실)
    - 분기순이익
    - 반기순이익
    - 지배기업 소유주지분
    - 계속영업당기순이익
  equity:
    - 자본총계
  liabilities:
    - 부채총계
